# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-deploy"
  build-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Set-up Node
        uses: actions/setup-node@v2
        with:
          node-version: "15.x"
      - run: |
          npm install
          npm run build-prod
        env:
          FB_API_KEY: ${{ secrets.FB_API_KEY }}
          FB_AUTH_DOM: ${{ secrets.FB_AUTH_DOM }}
          FB_PROJ_ID: ${{ secrets.FB_PROJ_ID }}
          FB_STOR_BUCK: ${{ secrets.FB_STOR_BUCK }}
          FB_MESS_SEND_ID: ${{ secrets.FB_MESS_SEND_ID }}
          FB_APP_ID: ${{ secrets.FB_APP_ID }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
          BACKEND_URI: ${{ secrets.BACKEND_URI }}
          BACKEND_REDIRECT_PATH: ${{ secrets.BACKEND_REDIRECT_PATH }}
          
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true
        
      # Runs a set of commands using the runners shell
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: dist
          fqdn: vbfy.viens.ml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
